# Service registers under this name
# Control the InternalResourceViewResolver:
spring:
  application:
    name: product-api
# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 8080